### PR TITLE
Moved the "STACK-Maxima started" printing to the end of loading of ad…

### PR DESCRIPTION
**Pull request by aharjula**
…ditional libraries.

This is for the issue #162.

### CODE REVIEW

**Comment by aharjula** [comment]
Argh... there are plenty of install and upgrade related scripts that try to find that string from stackmaxima.mac... so wait for another version.

**Comment by timhunt** [comment]
Why not get it to output an additional string, like "All libraries loaded"? Then you don't have to change the existing strings.

**Comment by aharjula** [comment]
In that case we would need to warn all the users of MaximaPool about the change in the logic of the "STACK-Maxima started" string. As it no longer marks the point where the maxima is actually ready for use. Somehow I would like to keep that string sensible and meaning what it seems to mean instead of minimising code changes and adding quirks. 

Basically, I read that string as a promise and we are not keeping that promise but we should and we can. But if we intend to not keep that promise we should just remove it from the world, which would again cause issues on the Pool side.

**Comment by timhunt** [comment]
The patches look OK to me (apart from some whitespace that is not quite right.)

**Comment by sangwinc** [comment]
Thanks Matti.

**Pull request merged**
