### PR TITLE
Fix unit tests for Maxima 5.41.0 and plugin version 4.3.8

### PR DESCRIPTION
**Pull request by golenkovm**
This is a fix candidate for the issue #720

### CODE REVIEW

**Comment by aharjula** [comment]
Sorry but no `3.0E+2` -> `3.E+2` is not something we want that is a sign of bad float handling in a LISP+Maxima combination. The test is not wrong the logic is if it cannot provide the correct output for that LISP+Maxima combination.

**Comment by sangwinc** [comment]
Matti,
Sorry, but my WIP commit just added in ignoring the missing zero, e.g. here: https://github.com/maths/moodle-qtype_stack/commit/7d039d9ef0e58d0f7cf034f52184d3414ab5c55f#diff-cbec917988f4e4d83d380ce16ce24839e5eafe01528dbfabf0455e1883157bdeR202
If you think I've made a mistake here, please let me know and I'll revert this WIP.

**Comment by aharjula** [comment]
Chris,
Well that fixes the tests, but should we not also fix the presentation for actual use? Is this not a case that only applies to the formatting rules that do not actually define the number of digits to display `"~a"` etc., maybe the Maxima side logic we have for formating the numbers should include special handling to fix those patterns if the problem is present in the LISP. Maybe the Maxima side logic sould simply do a test format of a suitable float to detect if this problem exists and if it exists replace the function with one that overrides those specific patterns.

**Comment by cameron1729** [comment]
Since #935 has been merged, this one can be closed :)

**Pull request closed without merging**
