### PR TITLE
Iss743 (and 1252) - Broken review on log in as + iframes broken by forceclean 

### PR DESCRIPTION
**Pull request by EJMFarrow**
#743 #1252 'Log in as' sets forceclean to true for security. Forceclean wipes the stack-iframe-holder id (and also any data-attributes so we can't use those instead).

I've added the id as a class as well so we can fall back to searching for that if the id isn't available. It feels like the issue is over-zealousness on forcecleans part but this gets us round it in a backwards compatible way.

Also fix another error on 'log in as' where JS was attempting to hide an element that wasn't there.

### CODE REVIEW

**Comment by timhunt** [comment]
Here is a question:

Why are we calling Moodle format_text - which is what is doing the force cleaning - **after** we are generating other bits of HTML for widgts?

Normally format_text should only be called on the bits of user-input HTML.

(Sorry, I don't remember in detail how STACK works any more.)

**Comment by aharjula** [comment]
Well as far as I understand it has always been called and thus will always be called, based on certain someones initial examples of how to build a renderer back in the early days of STACK3...

More seriously though I thought we are calling it so that the filters get applied, filters like multilang and MathJax and whatever else there is in play within the questiontext. Which is nice as then people can bolt whatever they want into the Moodle filter system and have it also working in STACK within that Moodle.

Is there an alternative way for calling just the filters but not the clean thing?

**Comment by timhunt** [comment]
"Is there an alternative way for calling just the filters but not the clean thing?"

That is not the right qestion to ask. The question is

"How can we get it to apply to the bits of the question were we want filters appied, without applying to technical bits of HTML we are creating which we don't want messed up?"

**Comment by aharjula** [comment]
Sounds like every CASText-block creator will be very happy. Basically, we need to carry with us from the individual block level the knowledge of which parts of the output are to be protected. We also must make it so that the question author cannot use that protection to skip "forceclean", basically, one must target it with utmost care in the blocks. This will mean that there will be new internal-blocks for those that need to signal this sensitivity during the compile phase and a change to the postprocess phase, the function signature for that will need to change to allow passing over information of these protected things.

Basically, we cannot know what sort of elements or syntax a given future block might need protected and we cannot be certain that these do not overlap, so the definition of the placeholders that will be in place during `format_text` will need to happen at the block level and those definitions will need to be passed around which will be fun but at least we then we will have a systematic way to skip this.

I'll do this next week and fix my blocks, but blocks that are not originally mine will need to decide on their own if they will do similar protections.

For those wishing to comment, this is the future:
 1. When postprocessing an evaluated bit of CASText one needs to give it a "placeholder"-object.
 2. Blocks can ask that object for unique placeholders to use in their output and register the original content into it.
 3. The return product from the postprocessing is now not directly usable as it might contain placeholders, but it should be filterable.
 4. After filtering one asks the "placeholder"-object to place things back.

Basically, every place that uses CASText will need to do that. There will be holders in various places for keeping track of those "placeholder"-objects.

**Comment by aharjula** [comment]
https://github.com/maths/moodle-qtype_stack/pull/1272/commits/a1a3feff706f55e25316dfed9998bae66db5b5db should make the CASText system able to mark things it does not want to be filtered.

At least in my tests I managed to have a functioning IFRAME and a missing id from a manual element in the same question, running with "log in as". And that fix should automatically apply to all the blocks of the IFRAME-family.

The next issue is how do we build `id` elements in arbitrary elements we might want to target from STACK-JS? Do we need a new variant of `[[quid/]]` that would print out something more like the whole `id="...."` bit, but how would the placeholder for that stay in place, obviously the value of the `id`-attribute won't stay in place? Any ideas on how to do [this](https://github.com/maths/moodle-qtype_stack/issues/1144#issuecomment-2011626280) if the usage around the value coming from the system needs to be author sourced and thus needs to go though filters?

**Comment by EJMFarrow** [comment]
Digging into what forceclean is actually doing, I think we can set the option `allowid` so the id doesn't get cleaned:
https://github.com/moodle/moodle/blob/0eacab846eebff126512f9738e26accef916e39b/lib/weblib.php#L1111
http://htmlpurifier.org/live/configdoc/plain.html#Attr.EnableID

**Comment by aharjula** [comment]
Ok. So from the point of view of STACK-JS I really want that `allowid` option to be on, everywhere we filter CASText content. And I cannot see a reason why it would lower security to turn that on. Without it too many things become impossible, and there must be a way for a teacher to see what a particular student sees.

For larger generated HTML constructs that need to be secured and that come from CASText blocks we still need that placeholder logic, even if the current issues can be solved with just `allowid`. There might be blocks coming in the near future that will require larger HTML segment protection, and even if there were not we might now finally protect even against the HTML-tidy filter, though whether it lets `id`s through is another matter.

We will never protect anything author-generated that is not going to sandbox iframes from these filters. Anything other than those `id`-attributes that is.

**Comment by EJMFarrow** [comment]
Yes, that sounds good. The stripping of the ids doesn't seem to be about security but about ensuring uniqueness and you've already dealt with that.

**Comment by aharjula** [comment]
https://github.com/maths/moodle-qtype_stack/pull/1272/commits/d50548b14f52018cb0678b25d0b9508bdcd5c38b adds that `allowid` to that options and things do indeed seem to work.

To me, this seems ready, but for style points we need to decide:
 1. Will we revert that `class` attribute workaround?
 2. Do we want to override this [`format_text`](https://github.com/moodle/moodle/blob/67f5ee3cec6f1701bbbf1b6d57216a3d291e8802/question/type/questionbase.php#L440) or should we call the base implementation directly in our renderer?
 3. Is there anything else we might not want to clean? I, for one, don't think so, but maybe someone else has ideas?

**Comment by EJMFarrow** [comment]
Hi @aharjula,

This looks good. I'll revert the class attribute workaround. I'd be happy sticking with overriding question->format_text as I think that makes it clearer what's going on. Can't think of anything else that needs protected.

**Pull request merged**
