### PR TITLE
Fix for JavaScript errors in Deferred feedback mode

### PR DESCRIPTION
**Pull request by timhunt**
I think this is the fix for the JavaScript error that George reported by email. However, I have not really tested it enough yet (and I am not sure I have time to) so not adding it to master yet.

I note that Behat was failing on Travis, which might have been because if this issue.

### CODE REVIEW

**Comment by timhunt** [comment]
Travis build here: https://travis-ci.org/github/maths/moodle-qtype_stack/builds/727833805

I had to move grunt check to CODEKNOWNFAILS becuase Chris has copied and pasted all the jQuery-UI CSS into STACK's CSS file. I am not sure that is a good idea.

**Comment by sangwinc** [comment]
Thanks Tim, for looking at this so quickly.

> Chris has copied and pasted all the jQuery-UI CSS into STACK's CSS file.
Sorry if I messed up here!  Do you mean this?
https://github.com/maths/moodle-qtype_stack/blob/master/styles.css#L516
Looking at the history, this was to fix issue #468.

**Comment by aharjula** [comment]
Have to wonder what we would do with jQuery-UI CSS if we do not have the matching JS (and we do not want it) and based on my trials that will not mix well with Moodle at all. Maybe someone should track the uses of those style-classes and rewrite them and only them with a STACK-specific prefix in the name.

One would guess that that particular injection of CSS only meant to inject [these](https://github.com/maths/moodle-qtype_stack/blob/0cdabea7cdce84842d0924d0cc1c590dfcaed521/styles.css#L815-L865) but even then where are those used?

Chris do we have a style-test question that has all the possible STACK-styles in it? All the inputs with all the style affecting options and all the feedback-forms as well as all the new system-level styles? Using such it should be simple to go through the document and spot the rules in that CSS that are not being used, also would work as a style document for a quick check of browser compatibility. As you have been adding style maybe you should produce such a question and take screenshots of it being rendered in the form you expect it to look. Screenshots for the Moodle themes that come with the default install should be enough.

**Comment by sangwinc** [comment]
Tim,
I think we can now delete this branch?  Thank you so much for fixing this so quickly.
Chris

**Comment by timhunt** [comment]
Yes. Branch can now go. In fact, I just clicked the button.

**Pull request merged**
