### PR TITLE
Force math formulas input directionality to LTR, also in RTL mode.

### PR DESCRIPTION
**Pull request by nadavkav**
Suggested fix for RTL mode, in which all math formulas need to be input in LTR mode (text directionality)

### CODE REVIEW

**Comment by sangwinc** [comment]
Thank you very much indeed.  Very sensible!

Should that be in the other input types as well.  What would you like to do about text areas for example?

**Comment by nadavkav** [comment]
I was wondering if it might be better to add a class to the input element (and all other input types) and have this fixed with a CSS selector, and not inlined CSS, what do you think?

Also, we need to make sure that some of the question creator forms input fields are also keeping their alignment and directionality to the left in RTL mode.

**Comment by nadavkav** [comment]
I have pushed a better fix for this issue, please review.

**Comment by timhunt** [comment]
I think this is a good change.

The better fix is better ;-)

**Comment by sangwinc** [comment]
Thank you,
Chris

**Comment by nadavkav** [comment]
Thank you @timhunt and @sangwinc :-)

**Pull request merged**
